apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.serviceName }}
  type: NodePort
  ports:
    - name: http
      targetPort: {{ .Values.containerPort }}
      port: {{ .Values.servicePort }}