name: Master pipeline
on:
  push:
  pull_request:
    types: [ reopened ]

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: eu-central-1
  CLOUDFRONT_DISTRIBUTION: E105UU8V5LGPMZ
  S3_BUCKET: s3://frontend-991225504892

jobs:
  build:
    name: Build static website
    runs-on: ubuntu-latest
    container: docker.io/node:18-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build static website
        run: |
          set -uex
          yarn
          yarn build

      - name: Upload built website as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  s3-upload:
    name: Upload static website to S3
    if: ${{ github.ref_name == 'master' }}
    needs:
      - build
    runs-on: ubuntu-latest
    container: ghcr.io/latin-ua/docker_images/terraform_pipeline:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download a static website artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Upload to S3
        run: |
          set -uex
          source assume-role.sh
          aws s3 sync dist/ "${S3_BUCKET}" --delete
          aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION" --paths "/*"