name: Master pipeline
on:
  push:
  pull_request:
    types: [ reopened ]

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  IMAGE_VERSION: ${{ github.sha }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  build-and-push-image:
    name: Build and push image
    if: ${{ github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

  helmfile-diff:
    name: Show k8s diff
    runs-on: ubuntu-latest
    container: ghcr.io/latin-ua/docker_images/terraform_pipeline:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run helmfile diff
        run: |
          source assume-role.sh
          aws eks update-kubeconfig --name main-cluster
          helmfile diff

  helmfile-apply:
    name: Apply changes to k8s
    if: ${{ github.ref_name == 'master' }}
    needs:
      - build-and-push-image
      - helmfile-diff
    runs-on: ubuntu-latest
    container: ghcr.io/latin-ua/docker_images/terraform_pipeline:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run helmfile apply
        run: |
          source assume-role.sh
          aws eks update-kubeconfig --name main-cluster
          helmfile apply